version: '3'
services:
  brazillian-orders-api-deployment:
    ports:
      - "${API_PORT}:${CONTAINER_PORT}"
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: savepeter2/brazillian-orders-api-deployment:latest
    volumes:
      - ./data:/Brazillian_Orders_Peter/data
    container_name: api-deployment-container
    entrypoint: ["/Brazillian_Orders_Peter/entrypoint.sh"]
    # environment:   
    #   - PORT=${CONTAINER_PORT:-8000}
    tty: true
    stdin_open: true
