name: Brazillian Orders CI/CD Pipeline to EC2 

on:
  push:
    branches: [ "orders_api_deployment" ]
  pull_request:
    branches: [ "orders_api_deployment" ]

jobs:
  build_and_push_docker_image:
    name: Login, Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Login Dockerhub
      uses: docker/login-action@v1
      with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_PASSWRORD }}
    - name: Build the Docker Image
      run: docker build -t brazillian_orders_deployment .
    - name: Push to Docker hub
      run: docker push savepeter2/brazillian_orders_deployment:latest

  notify:
    needs: build_and_push_docker_image
    runs-on: ubuntu-latest
    steps:
    - name: Pull Docker Image from Dockerhub
      run: sudo docker pull savepeter2/brazillian_orders_deployment:latest
    - name: delete the existing container
      run: docker rm -f api-deployment-container || true
    - name: Run the Docker Container with latest image being pulled
      run: docker run -d -p 8000:8000 --name api-deployment-container savepeter2/brazillian_orders_deployment:latest