name: Brazillian Orders CI/CD Pipeline to EC2 

on:
  push:
    branches: [ "orders_api_deployment" ]
  pull_request:
    branches: [ "orders_api_deployment" ]

jobs:
  build_and_push_image:
    name: Login, Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Login Dockerhub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker Image
      # run: docker build -t savepeter2/brazillian_orders_deployment:latest .
      run: docker compose build 
    # - name: Tag the image
    #   run: docker tag brazillian_orders_deployment savepeter2/brazillian_orders_deployment:latest
    - name: Push to Docker hub
      run: docker push savepeter2/brazillian-orders-api-deployment:latest

  pull_and_run_container:
    needs: build_and_push_image
    runs-on: ubuntu-latest
    steps:
    - name: Pull Docker Image from Dockerhub
      run: docker pull savepeter2/brazillian-orders-api-deployment:latest
    - name: delete the existing container
      run: docker rm -f api-deployment-container || true
    - name: Run the Docker Container with latest image being pulled
      run: docker run -p 8000:8000 --name api-deployment-container savepeter2/brazillian-orders-api-deployment:latest